'use strict';
(() => {
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const ns='http://www.w3.org/2000/svg',clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n)),mix=(a,b,t)=>a+(b-a)*t;
const smooth=(a,b,t)=>{const q=clamp((t-a)/(b-a));return q*q*(3-2*q)};
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const slides=$$('.slide'),deck=$('#deck'),parking=$('#interactive-parking');
let index=-1,returnFocus=null,toastTimer=0;
const SOURCES=[['01','01-使用AI的核心问题/使用AI的核心问题.md'],['02','02-AI的能力从哪里来/AI的能力从哪里来.md'],['03','03-信息输入与工具执行/信息输入与工具执行.md'],['04','04-需求表达与反馈闭环/需求表达与反馈闭环.md'],['05','05-任务执行与证据核验/任务执行与证据核验.md'],['06','06-行动选择与投入控制/行动选择与投入控制.md'],['07','07-课程制作与人机取舍/课程制作与人机取舍.md']];
const NOTES=[
'从一个看起来已完成、却不能放心使用的结果开始。课程不是提示词清单，而是判断框架：理解机制，辨认偏差，检查证据，控制下一次反馈前的投入。',
'第一篇的三个排查入口：材料或统计口径缺失，目标与决策用途不清，程序执行或交付失败。记录条数不能直接算作人数；要求重写不能修复文件未保存的问题。点击“材料 / 目标 / 执行”切换例子。',
'使用第二篇配套的“大语言模型简要说明”视频。训练形成参数中的能力和倾向，当前输入影响本次生成，通常的对话不等于即时改写参数。视频内容中文改编自 Grant Sanderson 的 Large Language Models explained briefly，原文字改编 Justin Sun；来源 https://www.3blue1brown.com/lessons/mini-llm/ 。这里没有将原静态插图复制为幻灯片。',
'第三篇的教学场景是文本模型加外部转写工具，不代表所有音频产品。用户只提出一次需求，应用组织两次模型调用；第一次生成工具请求，程序执行后把结果提供给第二次调用。路径不是文件内容，请求也不是成功执行。仓库第七篇记录的输入输出动画仍是静音预览；不得把它描述为已完成的有声成片。',
'移植第四篇交互的 smooth / Gaussian / channel 地形组合、三个机制的路径和具体对话。没有 iframe，没有原网页的侧栏、房间与二十项目录。保留语义漂移、特征纠缠、显式配平三个案例；A 是原策略。地形是因果解释用的教学比喻，不是模型真实内部空间或思维链观测。',
'同一地形在 B 策略下加入边界或验收条件，沟谷变化后回答路径才改变。语义漂移：日志错误只是清盘线索，不自动变成修证书的任务。特征纠缠：分别验收字段、直白表达、可用代码。显式配平：保留美观，同时限制为单文件交付。这里沿用交互沙盘的教学演绎，不把正文不同 A/B 对话拼成一段真实执行记录。',
'直接采用第五篇 F09：声音清楚，但演示切换得太快。它肯定声音，批评节奏。正确分类为练习与节奏，同类有 F02、F04、F06、F09、F11 共 5 条；不是 5 位独立学员。12 条是教学数据，不能推出总体满意度。计数与语义分类要分别核查；频次也不自动决定优先级。',
'散点使用第六篇 素材/七页演示内容.json 的全部 45 项任务，保留 investment、alignment、reason、cat。横轴是下一次有效反馈前的投入与承诺，不是累计成本；纵轴是有证据支持的对齐，不是“感觉讲清了”。分值为情境比较，50 只是排版分界。重合坐标仍保留，可用任务选择器访问每一项。',
'四个按钮是一种网页任务的讲述示意，坐标不是新增测量，也不会改写 45 项原始任务。可以按任意顺序选择，也可拖动深色演示点或用方向键移动。高暴露先缩小承诺；小样取得依据；满足用途即可停；只有依据充分且确有规模需求才扩大。认知四状态用于诊断依据缺口，不与行动四象限强制一一映射。',
'第七篇的制作取舍回到人的责任：确认解释目标，核对事实边界，判断表达是否讲清，以及何时停止。能渲染、能打开、看起来丰富，都不自动证明解释成立。结束时请听众用“方向、证据、取舍”判断自己的下一项任务。'
];
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200)}
function fit(){const s=Math.min(innerWidth/1600,innerHeight/900);deck.style.transform=`translate(-50%,-50%) scale(${s})`;deck.dataset.scale=s;terrain.resize()}
function go(n,updateHash=true){n=clamp(n,0,slides.length-1);if(n===index)return;terrain.leave();$$('video').forEach(v=>v.pause());if(index>=0){slides[index].hidden=true;slides[index].classList.remove('active')}parking.append($('#terrain-view'),$('#quadrant-view'));index=n;slides[n].hidden=false;slides[n].classList.add('active');if(n===4||n===5){$(n===4?'#terrain-before':'#terrain-after').append($('#terrain-view'));terrain.enter(n===5)}if(n===7||n===8){$(n===7?'#chart-map':'#chart-tour').append($('#quadrant-view'));chart.enter(n===8)}$('#prev').disabled=n===0;$('#next').disabled=n===slides.length-1;$('#page-number').textContent=`${String(n+1).padStart(2,'0')} / 10`;$('#slide-announcer').textContent=`第 ${n+1} 页：${slides[n].dataset.title}`;$('#key-hint').textContent=n===4||n===5?'地形内拖动旋转 · 空格播放/暂停 · ← → 翻页':n===8?'拖动深色演示点 · 选中后方向键微调 · F 全屏':'← → 翻页 · F 全屏 · N 讲者备注';if(updateHash){try{history.replaceState(null,'',`#${n+1}`)}catch{location.hash=String(n+1)}}}
$('#prev').onclick=()=>go(index-1);$('#next').onclick=()=>go(index+1);$$('[data-next]').forEach(b=>b.onclick=()=>go(index+1));
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('浏览器未允许全屏；仍可用方向键演讲。')}}$('#fullscreen').onclick=fullscreen;
function openOverlay(kind){if(terrain.state.playing)terrain.toggle();$$('video').forEach(v=>v.pause());returnFocus=document.activeElement;const c=$('#overlay-content');c.replaceChildren();const h=document.createElement('h2');h.textContent=kind==='notes'?`${String(index+1).padStart(2,'0')} / 讲者备注`:'课程总览';c.append(h);if(kind==='notes'){const p=document.createElement('p');p.textContent=NOTES[index];c.append(p);const label=document.createElement('p');label.textContent='本页依据 · Course 正式正文';c.append(label);slides[index].dataset.source.split(',').forEach(id=>{const file=SOURCES.find(s=>s[0]===id)?.[1];if(!file)return;const a=document.createElement('a');a.href='https://github.com/dabaige53/For-Use-AI/blob/main/Course/'+file;a.target='_blank';a.rel='noopener';a.textContent=file;const p=document.createElement('p');p.append(a);c.append(p)})}else{const grid=document.createElement('div');grid.className='slide-grid';slides.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${String(i+1).padStart(2,'0')}　${s.dataset.title}`;if(i===index)b.className='current';b.onclick=()=>{closeOverlay();go(i)};grid.append(b)});c.append(grid)}$('#overlay').showModal()}
function closeOverlay(){$('#overlay').close();returnFocus?.focus?.()}$('#overlay .close-overlay').onclick=closeOverlay;$('#notes').onclick=()=>openOverlay('notes');$('#overview').onclick=()=>openOverlay('overview');$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeOverlay()}});
addEventListener('keydown',e=>{if(e.defaultPrevented||$('#overlay').open)return;if(e.target.closest('input,select,textarea,video,[role=slider]'))return;if(e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(index+1)}else if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(index-1)}else if(e.key==='Home'){e.preventDefault();go(0)}else if(e.key==='End'){e.preventDefault();go(9)}else if(e.key.toLowerCase()==='f')fullscreen();else if(e.key.toLowerCase()==='n')openOverlay('notes');else if(e.key.toLowerCase()==='g')openOverlay('overview');else if(e.code==='Space'&&!e.target.closest('button')){e.preventDefault();if(index===4||index===5)terrain.toggle();else if(index===2||index===3)films[index===2?'llm':'io'].toggle();else go(index+1)}});
addEventListener('hashchange',()=>{const n=Number(location.hash.slice(1));if(Number.isInteger(n)&&n>=1&&n<=10)go(n-1,false)});addEventListener('resize',fit);document.addEventListener('fullscreenchange',fit);
const answers=['原始材料里，真的有这个数字吗？','你要的是改进决策，还是一篇宣传稿？','屏幕上写着完成，文件真的保存了吗？'];$$('[data-problem]').forEach(b=>b.onclick=()=>{$$('[data-problem]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#problem-answer').textContent=answers[Number(b.dataset.problem)]});
$$('[data-evidence]').forEach(b=>b.onclick=()=>{const right=b.dataset.evidence==='right';$$('[data-evidence]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#evidence-title').textContent=right?'归类依据，是原意。':'关键词，可能误导分类。';$('#evidence-title').style.color=right?'var(--ink)':'var(--risk)';$('#evidence-detail').textContent=right?'练习与节奏：F02、F04、F06、F09、F11，共 5 条记录；不能换算为 5 位学员。':'F09 肯定了声音，批评的是演示速度。声音问题的依据是 F01、F03，不包括 F09。'});
// Video files are local-only. Object URLs are never transmitted or persisted.
const media=JSON.parse($('#course-media').textContent),films={};
$$('[data-film]').forEach(host=>{const key=host.dataset.film,v=host.querySelector('video'),input=host.querySelector('input'),status=host.querySelector('.video-status');let objectURL='',loaded=false,pending=false;
 const showError=()=>{pending=false;host.classList.remove('is-playing');status.textContent=objectURL?'此文件暂时无法播放，请选择浏览器支持的 MP4 或 WebM。':'本地视频尚未连接。选择文件即可播放，不会上传。'};
 const play=async()=>{if(pending)return;pending=true;if(!loaded){v.src=media[key];loaded=true}try{await v.play()}catch(e){if(e.name!=='AbortError')showError()}finally{pending=false}};
 const toggle=()=>v.paused?play():v.pause();host.querySelector('.play-film').onclick=play;host.querySelector('.file-action').onclick=()=>input.click();
 input.onchange=()=>{const file=input.files?.[0];if(!file)return;v.pause();if(objectURL)URL.revokeObjectURL(objectURL);objectURL=URL.createObjectURL(file);v.src=objectURL;loaded=true;pending=false;status.textContent=file.name;v.load();play();input.value=''};
 v.addEventListener('playing',()=>{host.classList.add('is-playing');status.textContent=''});v.addEventListener('ended',()=>{host.classList.remove('is-playing');status.textContent='播放结束 · 点击重播'});v.addEventListener('error',showError);films[key]={toggle,pause:()=>v.pause(),dispose:()=>{if(objectURL)URL.revokeObjectURL(objectURL)}};
});
// Original core: Course/04-.../交互/思维地形.html, blob 4085e70d...
// Preserve smooth/Gaussian/channel geometry and A/B paths. Room, tables,
// directory and original UI are deliberately NOT copied or embedded.
const START=[-.84,.59],FORK=[-.21,.06],SHARED=[START,[-.76,.50],[-.65,.32],[-.54,.19],[-.40,.10],FORK];
const MECHANISMS={
 drift:{kind:'branch',name:'语义漂移',input:'根分区满了，请找出原因并释放磁盘空间。',context:'日志里反复出现 SSL 与 DNS 报错；排查开始转向证书。',strategy:'当前唯一目标是清理磁盘。SSL 异常只作为日志暴增的证据。',before:'开始修复证书与 DNS，清盘任务被遗忘。',after:'定位膨胀日志，安排日志轮转，回到清盘目标。',tagA:'线索，不自动等于新任务。',tagB:'重申目标，让旁支回到证据的位置。',path:[[.02,.20],[.26,.43],[.48,.48]],route:[[-.08,-.18],[.30,-.35],[.60,-.45]]},
 entangle:{kind:'venn',name:'特征纠缠',input:'以严谨的架构标准设计一个用户注册接口。',context:'DDD、防腐层、CQRS 与论文式说明被一起激活。',strategy:'分别验收：字段边界清晰、表达直白、代码直接可用。',before:'生成 500 行架构模板，难以直接使用。',after:'交付清楚的接口字段、校验与错误响应。',tagA:'想要的特点，也可能带出负担。',tagB:'分开验收，而不是重复形容词。',path:[[.03,-.02],[.25,.18],[.20,.27]],route:[[-.01,-.30],[.21,-.34],[.39,-.28]]},
 balance:{kind:'balance',name:'显式配平',input:'写一个炫酷、有现代科技感的番茄钟网页。',context:'方案引入 React、Tailwind CSS、Framer Motion 及安装步骤。',strategy:'我是小白，简单点。一个双击可用的 HTML 文件即可。',before:'用户无法完成终端与 npm 环境配置。',after:'直接交付包含样式和交互的单文件番茄钟。',tagA:'美观的要求，带出了工程复杂度。',tagB:'保留美观，降低交付门槛。',path:[[.05,.04],[.20,.26],[.35,.34]],route:[[.03,-.17],[.25,-.27],[.42,-.29]]}
};
const G=(x,z,a,b,sx=.23,sz=sx)=>Math.exp(-.5*(((x-a)/sx)**2+((z-b)/sz)**2));
function pathDist(x,z,p){let d=Infinity;for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i],dx=b[0]-a[0],dz=b[1]-a[1],u=clamp(((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz||1));d=Math.min(d,(x-a[0]-u*dx)**2+(z-a[1]-u*dz)**2)}return Math.sqrt(d)}
function catmull(p){const out=[];for(let i=0;i<p.length-1;i++)for(let k=0;k<12;k++){const t=k/12,a=p[Math.max(0,i-1)],b=p[i],c=p[i+1],d=p[Math.min(p.length-1,i+2)];out.push([0,1].map(j=>.5*(2*b[j]+(-a[j]+c[j])*t+(2*a[j]-5*b[j]+4*c[j]-d[j])*t*t+(-a[j]+3*b[j]-3*c[j]+d[j])*t*t*t)))}out.push(p.at(-1));return out}
function along(p,u){const j=clamp(u)*(p.length-1),i=Math.min(p.length-2,Math.floor(j));return [mix(p[i][0],p[i+1][0],j-i),mix(p[i][1],p[i+1][1],j-i)]}
const terrain=(()=>{const canvas=$('#terrain-canvas'),ctx=canvas.getContext('2d');const NX=38,NZ=30,ZMIN=-.85,ZMAX=.78;let active=false,after=false,key='drift',t=1,playing=false,raf=0,last=0,paintStamp=0,phaseKey='',yaw=.10,pitch=.67,zoom=1,dpr=1,drag=null,renderCount=0,grid=[],history=catmull(SHARED),branchA,branchB;
 function prepare(){const m=MECHANISMS[key];branchA=catmull([FORK,...m.path]);branchB=catmull([FORK,...m.route]);grid=[];for(let j=0;j<=NZ;j++)for(let i=0;i<=NX;i++){const x=-1+2*i/NX,z=mix(ZMIN,ZMAX,j/NZ);grid.push({x,z,h:0,hist:pathDist(x,z,SHARED),bd:pathDist(x,z,[FORK,...m.path]),ad:pathDist(x,z,[FORK,...m.route])})}phaseKey=''}
 function phases(){return {a:smooth(.125,.18,t),b:smooth(.35,.405,t),c:after?smooth(.61,.665,t):0,d:after?smooth(.725,.78,t):0,e:after?smooth(.84,.895,t):0}}
 function field(v,f){const m=MECHANISMS[key],{x,z,hist,bd,ad}=v,{a,b,c,d,e}=f,trench=(q,w=.105)=>Math.exp(-q*q/(2*w*w));const risk=G(x,z,...m.path.at(-1),.24),goal=G(x,z,...m.route.at(-1),.25);let out=-.18*(x+.84)*a-.28*a*trench(hist)-.24*b*trench(bd)-.35*b*risk;if(m.kind==='branch')out+=-.55*b*b*trench(bd,.14)-.15*b*G(x,z,.23,.60,.18)+c*(.48*trench(bd,.15)-.76*trench(ad)-.30*goal+.40*G(x,z,.29,.21,.13,.24));else if(m.kind==='venn'){out-=b*(.37*G(x,z,.03,.10,.22)+.43*G(x,z,.27,.26,.23)+.36*G(x,z,.20,.48,.22));out+=c*.26*G(x,z,.17,.26,.35);out-=(.35*c+.20*d+.17*e)*trench(ad,.10);out+=c*.32*G(x,z,.21,-.02,.09,.23)}else if(m.kind==='balance'){out-=b*.55*G(x,z,.38,.36,.21);out+=c*(.62*G(x,z,.38,.36,.22)-.60*trench(ad,.16)-.18*goal)}return clamp(out,-1.2,1.18)}
 function ground(x,z){const gx=clamp((x+1)*NX/2,0,NX-.00001),gz=clamp((z-ZMIN)/(ZMAX-ZMIN)*NZ,0,NZ-.00001),i=Math.floor(gx),j=Math.floor(gz),u=gx-i,v=gz-j;const a=grid[j*(NX+1)+i].h,b=grid[j*(NX+1)+i+1].h,c=grid[(j+1)*(NX+1)+i].h,d=grid[(j+1)*(NX+1)+i+1].h;return u+v<=1?a+(b-a)*u+(c-a)*v:d+(c-d)*(1-u)+(b-d)*(1-v)}
 function project(x,h,z){x*=1.15;z*=.90;const rx=x*Math.cos(yaw)-z*Math.sin(yaw),rz=x*Math.sin(yaw)+z*Math.cos(yaw),s=330*zoom;return [500+rx*s,330+rz*Math.sin(pitch)*s-h*Math.cos(pitch)*s,rz]}
 const color=(v,f)=>{const risk=G(v.x,v.z,...MECHANISMS[key].path.at(-1),.35)*f.b*(1-.85*f.c),depth=clamp(-v.h/1.2),base=[207-49*depth,215-44*depth,191-44*depth];return base.map((n,i)=>Math.round(mix(n,[181,137,112][i],risk*.43)))};
 function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.6;ctx.stroke()}}
 function draw(){if(!active||!ctx)return;renderCount++;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,1000,570);const f=phases();for(const v of grid)v.h=field(v,f);ctx.save();ctx.translate(500,415);ctx.scale(1,.26);const shadow=ctx.createRadialGradient(0,0,5,0,0,405);shadow.addColorStop(0,'#46593d25');shadow.addColorStop(1,'#46593d00');ctx.fillStyle=shadow;ctx.beginPath();ctx.arc(0,0,405,0,Math.PI*2);ctx.fill();ctx.restore();
 const tris=[];for(let j=0;j<NZ;j++)for(let i=0;i<NX;i++){const a=grid[j*(NX+1)+i],b=grid[j*(NX+1)+i+1],c=grid[(j+1)*(NX+1)+i],d=grid[(j+1)*(NX+1)+i+1];for(const vertices of [[a,b,c],[b,d,c]]){const points=vertices.map(v=>project(v.x,.40+v.h*.40,v.z));tris.push({vertices,points,depth:points.reduce((s,p)=>s+p[2],0)/3})}}
 const edges=[];for(let i=0;i<NX;i++){edges.push([grid[i],grid[i+1]]);edges.push([grid[NZ*(NX+1)+i],grid[NZ*(NX+1)+i+1]])}for(let j=0;j<NZ;j++){edges.push([grid[j*(NX+1)],grid[(j+1)*(NX+1)]]);edges.push([grid[j*(NX+1)+NX],grid[(j+1)*(NX+1)+NX]])}edges.sort((a,b)=>project(a[0].x,0,a[0].z)[2]-project(b[0].x,0,b[0].z)[2]);for(const [a,b] of edges)poly([project(a.x,.40+a.h*.40,a.z),project(b.x,.40+b.h*.40,b.z),project(b.x,-.20,b.z),project(a.x,-.20,a.z)],'#b6c2a7');
 tris.sort((a,b)=>a.depth-b.depth);for(const tri of tris){const v=tri.vertices.reduce((s,v)=>({x:s.x+v.x/3,z:s.z+v.z/3,h:s.h+v.h/3}),{x:0,z:0,h:0});const rgb=color(v,f);const dh=tri.vertices[1].h-tri.vertices[0].h;poly(tri.points,`rgb(${rgb.map(n=>clamp(Math.round(n+dh*80),0,255)).join(',')})`,'#6c805613')}
 function trace(path,end,color,width=3,dashed=false){if(end<=0)return;ctx.beginPath();const count=Math.max(2,Math.ceil(path.length*end));for(let k=0;k<count;k++){const p=along(path,k/(count-1)*end),q=project(p[0],.40+ground(...p)*.40+.014,p[1]);k?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dashed?[5,6]:[]);ctx.stroke();ctx.setLineDash([])}
 let h=.5*smooth(.19,.26,t);if(t>.42)h=.5+.5*smooth(.42,.515,t);let u=smooth(after?.68:.57,after?.98:.91,t);const branch=after?branchB:branchA;trace(history,h,'#435b3d',3);if(after&&f.c>.05)trace(branchA,1,'#aa645b60',2,true);trace(branch,u,after?'#2d6650':'#855e48',4);
 const p=u>0?along(branch,u):along(history,h),q=project(p[0],.40+ground(...p)*.40+.031,p[1]);ctx.fillStyle='#233e3322';ctx.beginPath();ctx.ellipse(q[0]+2,q[1]+7,12,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#233e33';ctx.beginPath();ctx.arc(q[0],q[1]-3,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fbfcf7';ctx.beginPath();ctx.arc(q[0]-2,q[1]-6,2,0,Math.PI*2);ctx.fill();
 const m=MECHANISMS[key];const points=[{pos:START,label:'原任务',color:'#607254'},{pos:m.path.at(-1),label:'旁支',color:'#a16d58'},{pos:m.route.at(-1),label:'目标',color:'#386b53'}];ctx.font='21px "PingFang SC","Noto Sans CJK SC",sans-serif';ctx.textAlign='center';for(const item of points){const p=project(item.pos[0],.40+ground(...item.pos)*.40,item.pos[1]);ctx.fillStyle=item.color;ctx.beginPath();ctx.arc(p[0],p[1]-3,3,0,Math.PI*2);ctx.fill();ctx.fillText(item.label,p[0],p[1]-24)}
 const events=[{time:.105,pos:[-.65,.32]},{time:.33,pos:FORK},...(after?[{time:.59,pos:m.route[0]}]:[])];for(const e of events){if(t<e.time-.08||t>e.time+.10)continue;const fall=1-smooth(e.time-.08,e.time,t),p=project(e.pos[0],.40+ground(...e.pos)*.40+fall*.65+.035,e.pos[1]);ctx.fillStyle='#bc9952';ctx.beginPath();ctx.arc(p[0],p[1]-6,8,0,Math.PI*2);ctx.fill();if(fall===0){ctx.strokeStyle='#bc9952';ctx.globalAlpha=1-smooth(e.time,e.time+.1,t);ctx.beginPath();ctx.ellipse(p[0],p[1],12+(t-e.time)*180,5+(t-e.time)*60,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}
 updateText();
 }
 function updateText(){const m=MECHANISMS[key];let phase=t<.30?0:t<.57?1:t<(after?.90:.72)?2:3;const stamp=`${key}-${after}-${phase}`;if(stamp!==phaseKey){phaseKey=stamp;$('#terrain-phase').textContent=['你的任务','旁支线索',after?'补充反馈':'方向开始偏离','观察结果'][phase];$('#terrain-quote').textContent=[m.input,m.context,after?m.strategy:m.before,after?m.after:m.before][phase];$('#terrain-tag').textContent=after?m.tagB:m.tagA;$('#terrain-tag').style.color=after?'var(--green)':'var(--risk)';$('#terrain-mode').textContent=after?'B · 加入反馈':'A · 原始策略'}$('#terrain-play').textContent=playing?'暂停':'播放演示';$('#terrain-play').setAttribute('aria-pressed',String(playing))}
 function frame(stamp){raf=0;if(!active||document.hidden)return;const dt=last?Math.min(.08,(stamp-last)/1000):0;last=stamp;if(playing){t=Math.min(1,t+dt/16);if(t===1)playing=false}if(stamp-paintStamp>32){draw();paintStamp=stamp}if(playing)raf=requestAnimationFrame(frame)}
 function wake(){if(!active)return;draw();last=0;if(playing&&!document.hidden&&!raf)raf=requestAnimationFrame(frame)}
 function resize(){const scale=Number(deck.dataset.scale)||1;dpr=clamp(devicePixelRatio*scale,1,2);canvas.width=Math.round(1000*dpr);canvas.height=Math.round(570*dpr);wake()}
 function toggle(){if(t>=1)t=0;playing=!playing;wake()}
 function enter(a){active=true;after=a;t=reduce.matches?1:.41;playing=!reduce.matches;phaseKey='';resize();wake()}
 function leave(){active=false;playing=false;cancelAnimationFrame(raf);raf=0;last=0}
 prepare();$('#terrain-play').onclick=toggle;$('#terrain-replay').onclick=()=>{t=0;playing=!reduce.matches;phaseKey='';wake()};$('#terrain-step').onclick=()=>{playing=false;const stops=[.25,.49,.71,1];t=stops.find(v=>v>t+.015)??.25;wake()};$('#terrain-reset').onclick=()=>{yaw=.10;pitch=.67;zoom=1;wake()};$$('[data-mechanism]').forEach(b=>b.onclick=()=>{key=b.dataset.mechanism;prepare();t=reduce.matches?1:.41;playing=!reduce.matches;$$('[data-mechanism]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));wake()});
 canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId);canvas.focus()});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw=clamp(drag.yaw+(e.clientX-drag.x)/350,-1,1);pitch=clamp(drag.pitch+(e.clientY-drag.y)/600,.35,1.1);draw()});const endDrag=()=>drag=null;canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);canvas.addEventListener('lostpointercapture',endDrag);canvas.addEventListener('wheel',e=>{if(!active)return;e.preventDefault();zoom=clamp(zoom-e.deltaY*.0008,.76,1.12);draw()},{passive:false});canvas.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();e.stopPropagation();toggle()}else if(e.key==='r'||e.key==='R'){$('#terrain-reset').click()}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom=clamp(zoom+.04,.76,1.12);draw()}else if(e.key==='-'){e.preventDefault();zoom=clamp(zoom-.04,.76,1.12);draw()}else if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();go(index+(e.key==='ArrowRight'?1:-1))}});
 document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(raf);raf=0;last=0;if(!document.hidden)wake()});reduce.addEventListener('change',()=>{if(reduce.matches){playing=false;draw()}});
 return {enter,leave,resize,toggle,get state(){return {active,after,key,t,playing,renderCount}},snapshot(time,mode=after){after=mode;t=clamp(time);playing=false;phaseKey='';draw()}};
})();
// Original 45 tasks, source coordinates unchanged. Only the separate demonstration
// point can be dragged. No randomized jitter or fabricated scores are introduced.
const TASKS=JSON.parse($('#course-tasks').textContent);
const chart=(()=>{const svg=$('#scatter'),select=$('#task-select'),points=$('#task-points'),custom=$('#custom-dot');let selected=20,category='all',tour=false,move=0,customPos=[25,25],dragging=false;
 const X=n=>188+n*12.84,Y=n=>408-n*3.62;
 const color=t=>t.alignment>=50?(t.investment>=50?'#9b793b':'#47796e'):(t.investment>=50?'#aa645b':'#78899a');
 const quadrant=(x,y)=>y>=50?(x>=50?'深度建设':'轻量交付'):(x>=50?'高暴露':'探索');
 const MOVES=[{pos:[78,18],title:'依据不足，先缩小承诺。',reason:'“整站重做，做到满意”没有可复用的验收标准。先隔离未知，不要继续扩大返工。'},{pos:[27,26],title:'先做一个可点击的小样。',reason:'用一页、一次交互，暴露布局与使用方式的分歧。原型也可以帮助发现需求。'},{pos:[27,80],title:'已经满足用途，就停在这里。',reason:'标准清楚、成果够用，不需要因为还可以生成，就继续扩成一套系统。'},{pos:[81,82],title:'依据充分，且确有规模需求。',reason:'两个前提同时成立，再分阶段建设，并在下一次大承诺之前设置检查点。'}];
 for(const task of TASKS){const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',X(task.investment));circle.setAttribute('cy',Y(task.alignment));circle.setAttribute('r','8');circle.setAttribute('fill',color(task));circle.setAttribute('tabindex','0');circle.setAttribute('role','button');circle.setAttribute('aria-label',`${task.text} 预期投入 ${task.investment}，对齐依据 ${task.alignment}`);circle.classList.add('task-point');circle.dataset.id=task.id;const title=document.createElementNS(ns,'title');title.textContent=task.text;circle.append(title);circle.addEventListener('click',()=>selectTask(task.id));circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.code==='Space'){e.preventDefault();e.stopPropagation();selectTask(task.id)}});points.append(circle)}
 function options(){select.replaceChildren();for(const t of TASKS.filter(t=>category==='all'||t.cat===Number(category))){const option=document.createElement('option');option.value=t.id;option.textContent=t.text;select.append(option)}select.value=String(selected)}
 function selectTask(id){selected=id;const task=TASKS.find(t=>t.id===id);if(!task)return;select.value=String(id);if(tour){tour=false;$('#map-tools').hidden=false;$('#tour-tools').hidden=true;$('#custom-group').toggleAttribute('hidden',true)}$$('.task-point').forEach(p=>{const t=TASKS.find(t=>t.id===Number(p.dataset.id)),match=category==='all'||t.cat===Number(category);p.style.opacity=match?'1':'.1';p.style.pointerEvents=match?'auto':'none';p.setAttribute('tabindex',match?'0':'-1');p.setAttribute('aria-pressed',String(t.id===id));p.setAttribute('r',t.id===id?'12':'8');p.classList.toggle('selected',t.id===id)});$('#selected-halo').toggleAttribute('hidden',false);$('#selected-halo').setAttribute('cx',X(task.investment));$('#selected-halo').setAttribute('cy',Y(task.alignment));$('#task-title').textContent=task.text;$('#task-meta').textContent=`${quadrant(task.investment,task.alignment)} · 预期投入 ${task.investment} / 对齐依据 ${task.alignment}`;$('#task-reason').textContent=task.reason}
 select.onchange=()=>selectTask(Number(select.value));$$('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;$$('[data-category]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(category!=='all'&&TASKS.find(t=>t.id===selected).cat!==Number(category))selected=TASKS.find(t=>t.cat===Number(category)).id;options();selectTask(selected)});
 function place(pos,manual=false){customPos=pos;const [x,y]=pos,cx=X(x),cy=Y(y);custom.setAttribute('cx',cx);custom.setAttribute('cy',cy);custom.setAttribute('aria-valuenow',Math.round(x));custom.setAttribute('aria-valuetext',`投入 ${Math.round(x)}，对齐 ${Math.round(y)}，${quadrant(x,y)}`);$('#custom-halo').setAttribute('cx',cx);$('#custom-halo').setAttribute('cy',cy);$('#custom-guides').setAttribute('d',`M188 ${cy}H${cx}V408`);$('#custom-label').setAttribute('x',cx>1320?cx-28:cx+28);$('#custom-label').setAttribute('y',cy<90?cy+34:cy-20);$('#custom-label').setAttribute('text-anchor',cx>1320?'end':'start');$('#task-meta').textContent=`${quadrant(x,y)} · 演示投入 ${Math.round(x)} / 对齐 ${Math.round(y)} · 非实测评分`;if(manual){$('#task-title').textContent=`现在，更接近“${quadrant(x,y)}”。`;$('#task-reason').textContent=y<50?(x>=50?'依据不足却承诺很多。先缩小下一步，找出最值得验证的假设。':'保持小规模探索，用比较、试作或查证换取依据。'):(x>=50?'仍需确认是否确有规模需求，并分阶段核验。':'先完成当前用途；满足标准就可以停止。');$$('[data-move]').forEach(b=>b.setAttribute('aria-pressed','false'))}}
 function chooseMove(n){move=n;tour=true;$('#map-tools').hidden=true;$('#tour-tools').hidden=false;$('#custom-group').toggleAttribute('hidden',false);$('#selected-halo').toggleAttribute('hidden',true);$$('.task-point').forEach(p=>{p.style.opacity='.22';p.style.pointerEvents='none';p.setAttribute('tabindex','-1');p.setAttribute('r','7');p.classList.remove('selected')});$$('[data-move]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.move)===n)));$('#task-title').textContent=MOVES[n].title;$('#task-reason').textContent=MOVES[n].reason;place(MOVES[n].pos)}
 $$('[data-move]').forEach(b=>b.onclick=()=>chooseMove(Number(b.dataset.move)));
 function pointer(e){const ctm=svg.getScreenCTM();if(!ctm)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(ctm.inverse());place([clamp((p.x-188)/12.84,0,100),clamp((408-p.y)/3.62,0,100)],true)}
 custom.addEventListener('pointerdown',e=>{e.preventDefault();dragging=true;custom.setPointerCapture(e.pointerId);custom.focus();pointer(e)});custom.addEventListener('pointermove',e=>{if(dragging)pointer(e)});for(const name of ['pointerup','pointercancel','lostpointercapture'])custom.addEventListener(name,()=>dragging=false);custom.addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();e.stopPropagation();const d=e.shiftKey?10:2;place([clamp(customPos[0]+(e.key==='ArrowRight'?d:e.key==='ArrowLeft'?-d:0),0,100),clamp(customPos[1]+(e.key==='ArrowUp'?d:e.key==='ArrowDown'?-d:0),0,100)],true)});
 options();return {enter(isTour){tour=isTour;$('#map-tools').hidden=isTour;$('#tour-tools').hidden=!isTour;$('#custom-group').toggleAttribute('hidden',!isTour);$('#chart-disclaimer').textContent=isTour?'拖动深色演示点，或选中后用方向键微调；其位置不修改原始 45 项任务。':'情境比较，不是实测评分；50 仅为排版分界。点击散点或用右上角选择任务。';if(isTour)chooseMove(move);else selectTask(selected)},get state(){return {selected,category,tour,customPos:[...customPos]}},selectTask};
})();
// New vector cover. No reused article SVGs, flowcharts, screenshots or fonts.
const contour=$('#contours');for(let ring=0;ring<24;ring++){const points=[];const size=48+ring*9;for(let i=0;i<=180;i++){const a=i*Math.PI*2/180,r=size*(1+.085*Math.sin(3*a+ring*.06)+.065*Math.cos(2*a-ring*.08));points.push(`${340+Math.cos(a)*r},${292+Math.sin(a)*r*.83}`)}const path=document.createElementNS(ns,'path');path.setAttribute('d','M'+points.join('L')+'Z');path.setAttribute('fill','none');path.setAttribute('stroke',ring%6===0?'#738b69':'#bcc8b1');path.setAttribute('stroke-width',ring%6===0?'1.4':'.8');contour.append(path)}const route=document.createElementNS(ns,'path');route.setAttribute('d','M119 438C177 430 225 341 279 342S371 392 395 317S360 240 388 169');route.setAttribute('stroke','#294d3b');route.setAttribute('stroke-width','3');route.setAttribute('fill','none');contour.append(route);for(const [x,y,r,fill] of [[119,438,5,'#829775'],[388,169,8,'#294d3b']]){const c=document.createElementNS(ns,'circle');for(const [k,v] of Object.entries({cx:x,cy:y,r,fill}))c.setAttribute(k,v);contour.append(c)}
addEventListener('pagehide',()=>{terrain.leave();Object.values(films).forEach(v=>v.dispose())});
window.CourseSlides=Object.freeze({goTo:n=>go(n-1),get state(){return {slide:index+1,terrain:terrain.state,chart:chart.state}},snapshotTerrain:(t,a)=>terrain.snapshot(t,a)});
const initial=Number(location.hash.slice(1));go(Number.isInteger(initial)&&initial>=1&&initial<=10?initial-1:0);fit();
})();
